filter k8s_services {
        if net ~ [ 192.168.253.0/24{32,32} ] then accept;
        reject;
}
template bgp k8s_peers {
        local as 64512;
        import filter k8s_services;
        export none;
        import limit 20 action block;
}
protocol bgp k8s_w00 from k8s_peers { neighbor 10.69.0.10 as 64513; }
protocol bgp k8s_w01 from k8s_peers { neighbor 10.69.0.11 as 64513; }
protocol bgp k8s_w02 from k8s_peers { neighbor 10.69.0.12 as 64513; }
protocol bgp k8s_w03 from k8s_peers { neighbor 10.69.0.20 as 64513; }
protocol bgp k8s_w04 from k8s_peers { neighbor 10.69.0.21 as 64513; }
protocol bgp k8s_w05 from k8s_peers { neighbor 10.69.0.22 as 64513; }
protocol bgp k8s_w06 from k8s_peers { neighbor 10.69.0.23 as 64513; }
protocol bgp k8s_w07 from k8s_peers { neighbor 10.69.0.24 as 64513; }
protocol bgp k8s_w08 from k8s_peers { neighbor 10.69.0.25 as 64513; }
protocol bgp k8s_w09 from k8s_peers { neighbor 10.69.0.26 as 64513; }
protocol bgp k8s_w10 from k8s_peers { neighbor 10.69.0.27 as 64513; }
protocol bgp k8s_w11 from k8s_peers { neighbor 10.69.0.28 as 64513; }
protocol bgp k8s_w12 from k8s_peers { neighbor 10.69.0.29 as 64513; }
protocol bgp k8s_w13 from k8s_peers { neighbor 10.69.0.30 as 64513; }
protocol bgp k8s_w14 from k8s_peers { neighbor 10.69.0.31 as 64513; }
protocol bgp k8s_w15 from k8s_peers { neighbor 10.69.0.32 as 64513; }
protocol bgp k8s_w16 from k8s_peers { neighbor 10.69.0.33 as 64513; }
protocol bgp k8s_w17 from k8s_peers { neighbor 10.69.0.34 as 64513; }
protocol bgp k8s_w18 from k8s_peers { neighbor 10.69.0.35 as 64513; }
protocol bgp k8s_w19 from k8s_peers { neighbor 10.69.0.36 as 64513; }
protocol bgp k8s_w20 from k8s_peers { neighbor 10.69.0.37 as 64513; }
protocol bgp k8s_w21 from k8s_peers { neighbor 10.69.0.38 as 64513; }
protocol bgp k8s_w22 from k8s_peers { neighbor 10.69.0.39 as 64513; }
protocol bgp k8s_w23 from k8s_peers { neighbor 10.69.0.40 as 64513; }