apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: linux-gw-253
  namespace: metallb-system
spec:
  myASN: 64513
  peerASN: 64512
  peerAddress: 192.168.253.254
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-253
  namespace: metallb-system
spec:
  addresses:
  - 192.168.253.150-192.168.253.155
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-253
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool-253